[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version = "0.8.19"

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"
localhost = "http://localhost:8545"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
